name: MinimalClans

version: 1.0
main: pw.ollie.minimalclans.MinimalClans

commands:
    clan:
        description: Base command for all clan commands

permissions:
    minimalclans.use:
        description: Allows access to /clan
